### ISSUE TITLE
database dump page shows no dumps

### ISSUE THREAD

**Issue by KiaraGrouwstra** [openkamer/openkamer#89]
hi there,
i see #55 added the option to download db dumps, which sounds way nicer than having to figure out how to deal with the Tweede Kamer XML API by oneself.
however, the [page](https://www.openkamer.org/database/dumps/) appears not to currently list any such dumps. is that a known issue?

background: i figured motion voting info could be used to create a voting advice application backed by actual data. :)

**Comment by bartromgens** [comment]
@KiaraGrouwstra Thanks for reporting this issue. The daily database dump is disabled because the size of the database caused some errors and performance issues. I will try and see if I can enable it again.

> which sounds way nicer than having to figure out how to deal with the Tweede Kamer XML API by oneself.

Also have a look at https://github.com/openkamer/tkapi for Python bindings for this API. Not the same as a dump, but potentially easier to use.

**Comment by bartromgens** [comment]
I just manually triggered a new database dump, see https://www.openkamer.org/database/dumps/

**Comment by bartromgens** [comment]
I have fixed the problem and re-enabled the daily dumps :crossed_fingers:
